# backend/mypy.ini
[mypy]
ignore_missing_imports = True
disallow_untyped_defs = True
exclude = (?x)(
    ^venv/
    | manage\.py$
    | settings\.py$
    | migrations/
    | tests\.py$
  )

# Подключаем плагины для Django и DRF
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "backend.settings" # Указываем путь к нашим настройкам